### ISSUE TITLE
cannot import name 'FSMContext' from 'aiogram.dispatcher'

### ISSUE THREAD

**Issue by PlugManYT** [NikolaySimakov/Store-bot#16]
Traceback (most recent call last):
  File "C:\GameizStore\app.py", line 3, in <module>
    import handlers
  File "C:\GameizStore\handlers\__init__.py", line 1, in <module>
    from .admin import dp
  File "C:\GameizStore\handlers\admin\__init__.py", line 1, in <module>
    from .add import dp
  File "C:\GameizStore\handlers\admin\add.py", line 2, in <module>
    from aiogram.dispatcher import FSMContext
ImportError: cannot import name 'FSMContext' from 'aiogram.dispatcher' (C:\Users\Cyber PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\aiogram\dispatcher\__init__.py)

**Comment by DaniilDonskoy** [comment]
Install aiogram==2.9.2 or aiogram==2.+
